apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-app
  template:
    metadata:
      labels:
        app: provider-app
    spec:
      containers:
      - name: provider-app
        image: provider-image
        ports:
        - containerPort: 8081
